# @format

services:
  douyin-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: douyin-video-downloader
    ports:
      - "9527:9527"
    environment:
      - PORT=9527
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9527 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # 可选：挂载日志目录
      - ./logs:/app/logs
    networks:
      - douyin-network

networks:
  douyin-network:
    driver: bridge
